// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdOXHIysejKZKbkQik7GBS3J-QFyNKSmE',
    appId: '1:114284606224:web:05265be58872bb1cd1ab95',
    messagingSenderId: '114284606224',
    projectId: 'taxiapp-192ae',
    authDomain: 'taxiapp-192ae.firebaseapp.com',
    storageBucket: 'taxiapp-192ae.appspot.com',
    measurementId: 'G-TSHM8QX5F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXdWkb95xjwWF5uFa4-dXzBsrEV2jbvE',
    appId: '1:114284606224:android:bd2835ef66421f80d1ab95',
    messagingSenderId: '114284606224',
    projectId: 'taxiapp-192ae',
    storageBucket: 'taxiapp-192ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvm1bXPnXU8GE1s5kH4p5GueQrD5G4VN8',
    appId: '1:114284606224:ios:7bd372f225639423d1ab95',
    messagingSenderId: '114284606224',
    projectId: 'taxiapp-192ae',
    storageBucket: 'taxiapp-192ae.appspot.com',
    iosClientId: '114284606224-kbvuf4t84l3srk93ahvehqsi9ppu39ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvm1bXPnXU8GE1s5kH4p5GueQrD5G4VN8',
    appId: '1:114284606224:ios:d347afc49ab0cadbd1ab95',
    messagingSenderId: '114284606224',
    projectId: 'taxiapp-192ae',
    storageBucket: 'taxiapp-192ae.appspot.com',
    iosClientId: '114284606224-kgoes3ie4041f4uqqbnj0aj3ue41sd17.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxi.RunnerTests',
  );
}
